### ISSUE TITLE
Invoking Client Functions?

### ISSUE THREAD

**Issue by RandyBuchholz** [dajuric/websocket-rpc#1]
I did a quick look at the code and samples and didn't see anything about invoking client-side functions from the server. Is this supported?

**Comment by dajuric** [comment]
You have multiple samples doing that. For example:

https://github.com/dajuric/websocket-rpc/blob/master/Samples/ClientJs/Program.cs

line 39:  await RPC.For<IProgressAPI>(this).CallAsync(x => x.WriteProgress((
float)p / 100));

where the remote client function (implemented in JavaScript) is called.
'This' selector is used to filter out other clients not associated with the
particular connection).

Best,
Darko

2018-01-15 14:22 GMT+01:00 Randy Buchholz <notifications@github.com>:

**Comment by RandyBuchholz** [comment]
Nice job BTW.

I saw that, but isn't that more of an Action call than Function call? What about getting a return value? Something like this (pseudo code):
```
// client
<input type="text" id="textbox" />

function getTextValue(elementName : string) : string {
   return getElementById(elementName).value;
}

// server
var clientText = client.Invoke("getTextValue", "textbox");
```

**Comment by dajuric** [comment]
Actually, you have more overloads of a single CallAsync function. This can
be seen here:
https://github.com/dajuric/websocket-rpc/blob/master/Source/WebSocketRPC.Base/RpcBinders/Base/IBinder.cs

so, both action and function calls including the async variants are covered.

So, I assume your question is can you get a return value or not.
The answer is yes, for sync and async functions and for both .NET and
JavaScript clients.

Samples:
https://github.com/dajuric/websocket-rpc/blob/master/Samples/MultiService/Site/Index.html
(lines 30, 36)

https://github.com/dajuric/websocket-rpc/blob/master/Samples/Serialization/Site/Index.html
(line 29 - where I actually return the whole image :))

If calling JavaScript client functions, the procedure is the same (how did I miss to put a  sample, hmmmm...). So, extend the client API like in:
https://github.com/dajuric/websocket-rpc/blob/master/Samples/ClientJs/Site/Index.html  (line 29)
but in your case return the actual value. That should be fine.

I hope that was helpful.
If you find the library useful, I would be grateful if you could star the repository or the CodeProject article.

2018-01-15 14:51 GMT+01:00 Randy Buchholz <notifications@github.com>:

**Comment by RandyBuchholz** [comment]
Cool. I'll take a look. It would be good to see an example. If you get a chance, can you show a simple example of doing a "read the browser and assign to a variable? (Like my example.)

With SignalR, sending the request for info and getting a response are two separate things. They don't support any type of synchronization. Not being able to do solicit->response->assign in one line is a powerful, missing feature for real RPC. 

I've stared both and hope to feature this in an article I am writing on Solicit-Response approaches to web apps.

**Comment by dajuric** [comment]
A sample is added. 
Take a look at the: https://github.com/dajuric/websocket-rpc/tree/master/Samples/ClientInfoJs

**Comment by RandyBuchholz** [comment]
Really nice, Darko! Looks like it does just what I need. I'm going to try integrating it into a Razor Pages thing I'm doing in Core. I'll let you know how that goes.
